test_size: 0.2
random_state: 0
features:
  -Location       
  -MinTemp      
  -MaxTemp        
  -Rainfall       
  -Evaporation    
  -Sunshine       
  -WindGustDir    
  -WindGustSpeed  
  -WindDir9am     
  -WindDir3pm     
  -WindSpeed3pm   
  -Humidity9am    
  -Pressure9am   
  -Pressure3pm    
  -Cloud9am       
  -Cloud3pm      
  -Temp9am       
  -Temp3pm       
  -RainToday      
  -ainTomorrow 